[project]
name = "release-tracker"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jinja2>=3.1.6",
    "packaging>=25.0",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
]
